### ISSUE TITLE
java.lang.IllegalArgumentException: Bound must be positive

### ISSUE THREAD

**Issue by hotsu0p** [hotsu0p/Architect-issues#3]
This is in the 2.0 beta
 
 will fix soon
 
```
 java.lang.IllegalArgumentException: Bound must be positive
        at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom.java:22)
        at hotsuop.architect.world.decorator.Spread32Decorator.getPositions(Spread32Decorator.java:17)
        at net.minecraft.world.gen.feature.PlacedFeature.method_39649(PlacedFeature.java:50)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature.java:55)
        at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature.java:44)
        at hotsuop.architect.world.gen.ArchitectChunkGenerator.generateFeatureStep(ArchitectChunkGenerator.java:508)
        at hotsuop.architect.world.gen.ArchitectChunkGenerator.generateFeatures(ArchitectChunkGenerator.java:432)
        at net.minecraft.world.chunk.ChunkStatus.method_20613(ChunkStatus.java:145)
        at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus.java:292)
        at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage.java:679)
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
        at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage.java:673)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem.java:62)
        at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor.java:91)
        at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor.java:146)
        at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor.java:102)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by hotsu0p** [comment]
Fixed
